language: php

php:
  - 7.1
  - 7.2
  - 7.3

env:
  matrix:
    - COMPOSER_FLAGS=""
    - COMPOSER_FLAGS="--prefer-lowest"

stages:
  - test
  - test with coverage
  - phpstan

before_install: phpenv config-rm xdebug.ini || echo "xdebug not available"

install: travis_retry composer update --optimize-autoloader --prefer-dist --prefer-stable --no-progress --no-interaction --no-suggest $COMPOSER_FLAGS -vv

script: vendor/bin/phpunit --colors --no-coverage

jobs:
  allow_failures:
    - php: nightly
  include:
    - php: nightly
      env: COMPOSER_FLAGS="--ignore-platform-reqs"

    - stage: test with coverage
      php: 7.1
      env: COMPOSER_FLAGS=""
      before_install: skip
      script: vendor/bin/phpunit --colors --coverage-clover=clover.xml --coverage-text
      after_success:
        - wget https://scrutinizer-ci.com/ocular.phar; php ocular.phar code-coverage:upload --format=php-clover clover.xml

    - stage: phpstan
      php: 7.1
      env: COMPOSER_FLAGS=""
      before_install: skip
      script: vendor/bin/phpstan analyse src/
